# Generated by Django 4.2 on 2023-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
