# Generated by Django 4.2 on 2023-06-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onestopsalon.category'),
        ),
    ]
