# Generated by Django 4.2 on 2023-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0005_salon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='onestopsalon/'),
        ),
    ]
