# Generated by Django 4.2 on 2023-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0006_alter_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='close',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='salon',
            name='open',
            field=models.TimeField(default=0),
        ),
    ]
