# Generated by Django 4.2 on 2023-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0007_salon_close_salon_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='close',
            field=models.TimeField(default='0'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='open',
            field=models.TimeField(default='0'),
        ),
    ]
