# Generated by Django 4.2 on 2023-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestopsalon', '0009_remove_salon_close_remove_salon_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='open_time',
        ),
        migrations.AddField(
            model_name='salon',
            name='closing',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
